window.CORA_SKILLS=Object.freeze({
FITNESSSTUDIO:{label:"Fitnessstudio",keywords:["fitnessstudio","fitness","training","mitglied","probetraining","kurs","gym"],fields:["trainingsziel","standort","probetraining","start","mitgliedschaft","kurse"],questions:["Was ist Ihr Trainingsziel?"],roi:"Probetraining, Mitgliedschaft und Kursinteresse vorqualifizieren."},
HANDWERK_SHK:{label:"Handwerk / SHK",keywords:["handwerk","shk","heizung","wärmepumpe","sanitär","bad","wartung","reparatur","installation","neubau","gasheizung"],fields:["leistung","projektart","objektart","bestehende anlage","plz/einsatzgebiet","zeitrahmen","kontakt"],questions:["Geht es um den Austausch einer bestehenden Heizung oder um einen Neubau?"],roi:"Leistung, Projektart und Einsatzgebiet vorqualifizieren."},
ELEKTRO:{label:"Elektrotechnik",keywords:["elektriker","elektro","elektrotechnik","photovoltaik","pv","wallbox","stromspeicher","smart home"],fields:["leistung","objektart","projektart","leistungsklasse","ort","zeitrahmen"],questions:["Welche Leistung benötigen Sie – z. B. PV, Wallbox, Elektroinstallation oder Smart Home?"],roi:"Projektart und Einsatzgebiet vorqualifizieren."},
BAU:{label:"Bau / Ausbau",keywords:["bauunternehmen","bau","ausbau","trockenbau","dachdecker","dach","maler","fenster","fassade","bodenleger"],fields:["gewerk","projektart","objekt","fläche","ort","zeitrahmen"],questions:["Um welches Bau- oder Ausbauprojekt geht es?"],roi:"Projektumfang und Terminbedarf strukturiert erfassen."},
RESTAURANT_HOTEL:{label:"Restaurant / Hotel",keywords:["restaurant","hotel","gastronomie","reservierung","zimmer","veranstaltung","tisch","übernachtung"],fields:["datum","personen","anlass","leistung","veranstaltung","zimmer"],questions:["Für welches Datum und wie viele Personen geht es?"],roi:"Reservierungen, Veranstaltungen und Anfragen vorqualifizieren."},
IMMOBILIEN:{label:"Immobilien",keywords:["immobilien","makler","wohnung","haus","objekt","kauf","miete","grundstück"],fields:["kauf/miete","objektart","lage","budget","zeitraum"],questions:["Suchen Sie zum Kauf oder zur Miete?"],roi:"Kauf-/Mietabsicht, Objekt, Lage und Budget erfassen."},
B2B_BERATUNG:{label:"B2B / Beratung",keywords:["b2b","beratung","agentur","dienstleistung","software","unternehmen","projekt","consulting"],fields:["unternehmen","projektart","ziel","umfang","zeitrahmen","budget"],questions:["Was soll mit dem Projekt konkret erreicht werden?"],roi:"Projektziel, Umfang und Entscheidungsprozess vorqualifizieren."},
KANZLEI:{label:"Kanzlei",keywords:["kanzlei","anwalt","rechtsanwalt","recht","mandat","rechtsberatung","notar"],fields:["themenbereich","allgemeines anliegen","gewünschter kontakt","dringlichkeit"],questions:["Um welchen allgemeinen Themenbereich geht es?"],roi:"Allgemeine Anliegen organisatorisch vorsortieren; keine individuelle Rechtsberatung."},
VERSICHERUNG:{label:"Versicherung / Finanzberatung",keywords:["versicherung","versicherungen","finanzberatung","finanzierung","kredit","vorsorge"],fields:["thema","bedarf","status","terminwunsch","kontakt"],questions:["Geht es um einen bestehenden Vertrag oder um einen neuen Bedarf?"],roi:"Bedarf und Beratungsanlass vorqualifizieren."},
ARZTPRAXIS:{label:"Arztpraxis / Gesundheit",keywords:["arzt","arztpraxis","zahnarzt","praxis","therapie","physio","medizin","gesundheit"],fields:["anliegen","terminart","standort","terminwunsch"],questions:["Geht es um einen Termin, allgemeine Praxisinformationen oder eine andere organisatorische Frage?"],roi:"Organisatorische Fragen und Terminwünsche strukturieren; keine Diagnose."},
BILDUNG:{label:"Bildung / Weiterbildung",keywords:["schule","weiterbildung","akademie","kursanbieter","seminar","bildung","studium","ausbildung"],fields:["kurs","ziel","start","format","voraussetzungen"],questions:["Für welchen Kurs oder welches Bildungsziel interessieren Sie sich?"],roi:"Kursinteresse und Voraussetzungen strukturiert erfassen."},
AUTO:{label:"Autohaus / Werkstatt",keywords:["autohaus","autohändler","werkstatt","fahrzeug","reifen","inspektion","service","leasing"],fields:["fahrzeug","leistung","service","termin","budget"],questions:["Geht es um Fahrzeugkauf, Service oder eine Reparatur?"],roi:"Serviceanlass, Fahrzeug und Terminwunsch erfassen."},
E_COMMERCE:{label:"E-Commerce",keywords:["online shop","onlineshop","e-commerce","shop","bestellung","retoure","produkt"],fields:["produkt","bestellung","kaufabsicht","retoure","kontakt"],questions:["Geht es um eine Produktfrage, Bestellung oder Retoure?"],roi:"Produktfragen und Kaufinteresse direkt beantworten."},
RECRUITING:{label:"Recruiting / Personal",keywords:["recruiting","personal","jobs","job","bewerbung","karriere","personalvermittlung"],fields:["rolle","erfahrung","standort","start","kontakt"],questions:["Geht es um eine offene Stelle, eine Bewerbung oder Personalbedarf?"],roi:"Kandidaten- und Arbeitgeberanfragen vorqualifizieren."},
TOURISMUS:{label:"Tourismus / Reise",keywords:["reisebüro","tourismus","urlaub","reise","ferienwohnung","tour"],fields:["ziel","datum","personen","budget","reiseart"],questions:["Wohin und für welchen Zeitraum möchten Sie reisen?"],roi:"Reiseanfragen nach Ziel, Zeitraum und Budget strukturieren."},
EVENT:{label:"Events / Veranstaltungen",keywords:["event","veranstaltung","messe","hochzeit","catering","konferenz","tagung"],fields:["veranstaltung","datum","personen","ort","budget"],questions:["Welche Art von Veranstaltung planen Sie und für wann?"],roi:"Eventanfragen nach Umfang und Termin qualifizieren."},
REINIGUNG:{label:"Gebäudereinigung",keywords:["reinigung","gebäudereinigung","facility","cleaning","hausmeister"],fields:["objekt","fläche","frequenz","ort","leistung"],questions:["Welche Fläche und welcher Reinigungsumfang sollen betreut werden?"],roi:"Objekt, Fläche und Frequenz für Angebotsanfragen erfassen."},
LOGISTIK:{label:"Logistik / Transport",keywords:["logistik","transport","spedition","lager","kurier","lieferung","fracht"],fields:["sendung","route","volumen","termin","leistung"],questions:["Welche Transportleistung und welche Route benötigen Sie?"],roi:"Sendungsdaten und Transportbedarf vorqualifizieren."},
SOFTWARE_IT:{label:"IT / Software",keywords:["it","softwareentwicklung","webentwicklung","hosting","cybersecurity","cloud","app"],fields:["projekt","ziel","system","umfang","zeitrahmen"],questions:["Welches technische Problem oder Projekt soll gelöst werden?"],roi:"Projektziel, Systeme und Umfang vorqualifizieren."},
MARKETING:{label:"Marketing / Kreativagentur",keywords:["marketing","seo","social media","werbeagentur","branding","design","content"],fields:["kanal","ziel","umfang","budget","zeitrahmen"],questions:["Welches Marketingziel möchten Sie erreichen?"],roi:"Ziel, Kanäle und Projektumfang strukturiert erfassen."},
RECHNUNGSWESEN:{label:"Steuerberatung / Buchhaltung",keywords:["steuerberater","steuerberatung","buchhaltung","buchhalter","jahresabschluss","lohnabrechnung"],fields:["thema","unternehmen","umfang","periode","kontakt"],questions:["Geht es um laufende Buchhaltung, Lohn oder einen steuerlichen Themenbereich?"],roi:"Anliegen und Umfang für den Erstkontakt strukturieren."}
});
window.CORA_INTENTS={PRICE:/preis|preise|kosten|kostet|monat|setup|€|euro/i,ROI:/lohnt|roi|wirtschaft|rentiert|auszahl|ausgezahlt|umsatz|wert|rendite|einspar/i,DATA:/welche daten|welchen daten|welche angaben|datenschutz|personenbezogen|speicher|dsgvo|braucht cora.*daten/i,OFFER:/angebot|offerte|angebot anfordern/i,TEST:/testen|test|ausprobieren|demo|probieren/i,INTEGRATION:/integration|integrieren|einbinden|einbindung|website einbauen|anbindung|schnittstelle|crm|kalender/i,USE_CASE:/wie (kann|würde).*cora|wie.*helfen|was.*bringt|nutzen|vorteil/i,PACKAGE:/basic|pro|enterprise|paket|modell|welches.*geeignet|empfehl/i,OBJECTION:/kontaktformular|zu teuer|mitarbeiter|warum.*ki|kaum anfragen/i,COMPARISON:/vergleich|unterschied|vs\\.?|statt/i,PURCHASE:/buchen|kaufen|beauftragen|starten|termin|gespräch/i,CONTACT:/kontakt|anrufen|email|e-mail|melden/i,PROBLEM:/problem|schwier|zu wenig|manuell|zeitaufwand/i,INDUSTRY:/fitness|shk|heizung|restaurant|hotel|immobil|kanzlei|beratung|agentur|handwerk|elektro|pv|bau|auto|software|marketing|steuer/i,INFORMATION:/^(was|wie|wer|wann|wo|kann|gibt|ist|sind)/i,DEMO_FLOW:/echten ablauf|ablauf zeigen|durchspielen|beispiel/i};