window.CORA_SKILLS=Object.freeze({
  FITNESSSTUDIO:{id:"fitnessstudio",label:"Fitnessstudio",keywords:["fitnessstudio","fitness","training","mitglied","probetraining","kurs","gym"],fields:["trainingsziel","standort","probetraining","start","mitgliedschaft","kurse"],questions:["Wie viele Website-Anfragen oder Probetrainings erhalten Sie ungefähr pro Monat?"],useCases:["Probetraining vorqualifizieren","Mitgliedschaftsfragen beantworten","Kursinteresse erfassen"],objectionHandling:["Cora ergänzt vorhandene Kontaktformulare, statt sie zwingend zu ersetzen."],cta:"Anfrage vorbereiten"},
  KANZLEI:{id:"kanzlei",label:"Kanzlei",keywords:["kanzlei","anwalt","rechtsanwalt","rechtsberatung","mandat","recht"],fields:["themenbereich","allgemeines anliegen","gewünschter kontakt","dringlichkeit"],questions:["Um welchen allgemeinen Themenbereich geht es? Bitte keine vertraulichen Details eingeben."],useCases:["Erstkontakt strukturieren","allgemeine Informationen beantworten","Kontaktwunsch erfassen"],objectionHandling:["Keine individuelle Rechtsberatung simulieren."],cta:"Gespräch anfragen"},
  IMMOBILIEN:{id:"immobilien",label:"Immobilien",keywords:["immobilien","immobilienmakler","makler","wohnung","haus","objekt","kauf","miete"],fields:["kauf/miete","objektart","lage","budget","zeitraum"],questions:["Geht es um Kauf oder Miete?"],useCases:["Interessenten vorsortieren","Objektanforderungen erfassen","Besichtigungsanfragen strukturieren"],objectionHandling:["Cora ersetzt keine individuelle Immobilienberatung."],cta:"Anfrage vorbereiten"},
  HANDWERK_SHK:{id:"handwerk-shk",label:"Handwerk / SHK",keywords:["handwerk","shk","heizung","wärmepumpe","sanitär","bad","wartung","reparatur","installation","neubau"],fields:["leistung","projektart","objektart","bestehende anlage","plz/einsatzgebiet","zeitrahmen"],questions:["Geht es um den Austausch einer bestehenden Anlage, eine Reparatur oder einen Neubau?"],useCases:["Leistung erkennen","Projektart erfassen","Einsatzgebiet und Zeitraum aufnehmen"],objectionHandling:["Technische Angaben nur übernehmen, wenn sie vom Interessenten stammen oder freigegebenes Wissen vorliegt."],cta:"Anfrage vorbereiten"},
  AGENTUR:{id:"agentur",label:"Agentur",keywords:["agentur","werbeagentur","marketingagentur","kreativagentur"],fields:["leistung","projektart","ziel","umfang","zeitrahmen"],questions:["Welche Leistung soll Cora auf Ihrer Website hauptsächlich unterstützen?"],useCases:["Projektanfragen qualifizieren","Leistungsinteresse erkennen","Briefing-Daten vorbereiten"],objectionHandling:["Cora kann den Erstkontakt strukturieren, nicht die kreative Leistung ersetzen."],cta:"Gespräch anfragen"},
  UNTERNEHMENSBERATUNG:{id:"unternehmensberatung",label:"Unternehmensberatung",keywords:["unternehmensberatung","managementberatung","beratung","consulting"],fields:["themenbereich","ziel","unternehmen","umfang","zeitrahmen"],questions:["Welches konkrete Ziel soll mit dem Erstkontakt erreicht werden?"],useCases:["Beratungsbedarf einordnen","Projektumfang erfassen","Gesprächsanfragen strukturieren"],objectionHandling:["Cora unterstützt die Vorqualifizierung und ersetzt keine Beratung."],cta:"Gespräch anfragen"},
  HOTEL:{id:"hotel",label:"Hotel",keywords:["hotel","zimmer","übernachtung","tagungshotel"],fields:["datum","personen","zimmer","anlass","leistung"],questions:["Für welchen Zeitraum und wie viele Personen geht es?"],useCases:["Buchungsanfragen strukturieren","Veranstaltungsanfragen erfassen","Fragen zu freigegebenen Informationen beantworten"],objectionHandling:["Verfügbarkeit darf nur aus angebundenen oder freigegebenen Daten genannt werden."],cta:"Anfrage vorbereiten"},
  RESTAURANT:{id:"restaurant",label:"Restaurant",keywords:["restaurant","gastronomie","reservierung","tisch","speisekarte"],fields:["datum","personen","anlass","leistung"],questions:["Für welches Datum und wie viele Personen geht es?"],useCases:["Reservierungsanfragen vorqualifizieren","Anlass und Personenzahl erfassen","Allgemeine Fragen beantworten"],objectionHandling:["Keine Verfügbarkeit erfinden."],cta:"Reservierungsanfrage vorbereiten"},
  STEUERBERATUNG:{id:"steuerberatung",label:"Steuerberatung",keywords:["steuerberater","steuerberatung","steuerkanzlei","buchhaltung","jahresabschluss"],fields:["themenbereich","unternehmen","anliegen","zeitraum","kontaktwunsch"],questions:["Um welchen allgemeinen Bereich geht es: Buchhaltung, Jahresabschluss oder Steuerfrage?"],useCases:["Anliegen vorsortieren","Unternehmensdaten erfassen","Kontaktwunsch vorbereiten"],objectionHandling:["Keine individuelle Steuerberatung simulieren."],cta:"Gespräch anfragen"},
  ARZTPRAXIS:{id:"arztpraxis",label:"Arztpraxis",keywords:["arztpraxis","arzt","ärztin","arzttermin","praxis","sprechstunde"],fields:["anliegen","terminwunsch","standort","kontaktwunsch"],questions:["Geht es um einen allgemeinen Praxis-/Terminwunsch? Bitte keine sensiblen Gesundheitsdetails eingeben."],useCases:["Allgemeine Praxisinformationen beantworten","Terminwunsch strukturieren","Kontaktweg vorbereiten"],objectionHandling:["Keine medizinische Diagnose oder individuelle Behandlungsempfehlung simulieren."],cta:"Kontakt anfragen"},
  MAKLER:{id:"makler",label:"Makler",keywords:["makler","immobilienmakler","immobilien","objektvermittlung"],fields:["kauf/miete","objektart","lage","budget","zeitraum"],questions:["Suchen Sie ein Objekt zum Kauf oder zur Miete?"],useCases:["Suchprofil erfassen","Interessenten vorsortieren","Besichtigungsanfragen strukturieren"],objectionHandling:["Cora ersetzt keine persönliche Maklerberatung."],cta:"Anfrage vorbereiten"},
  SAAS:{id:"saas",label:"SaaS-Unternehmen",keywords:["saas","software-as-a-service","softwareunternehmen","b2b software","software"],fields:["produkt","unternehmen","use case","größe","projektziel"],questions:["Welche Art von Anfrage soll Cora auf Ihrer Website hauptsächlich qualifizieren?"],useCases:["Produktfragen beantworten","Demo-Anfragen qualifizieren","Use Case und Unternehmenskontext erfassen"],objectionHandling:["Cora ersetzt keine Produktberatung durch das Vertriebsteam."],cta:"Demo anfragen"},
  B2B:{id:"b2b",label:"B2B-Unternehmen",keywords:["b2b","geschäftskunden","industrieunternehmen","mittelstand","unternehmen"],fields:["unternehmen","projektart","ziel","umfang","zeitrahmen"],questions:["Was soll mit einer qualifizierten Website-Anfrage konkret erreicht werden?"],useCases:["B2B-Anfragen strukturieren","Projektbedarf erfassen","Vertriebsvorqualifizierung"],objectionHandling:["Cora unterstützt den Erstkontakt und die Qualifizierung."],cta:"Gespräch anfragen"},
  MITTELSTAND:{id:"mittelstand",label:"Mittelstand",keywords:["mittelstand","mittelständler","mittelständisches unternehmen"],fields:["unternehmen","ziel","leistung","umfang","zeitrahmen"],questions:["Welcher Website-Prozess soll zuerst verbessert werden: Fragen, Anfragen oder Lead-Qualifizierung?"],useCases:["Website-Anfragen strukturieren","Produkt-/Leistungsfragen beantworten","Lead-Qualifizierung"],objectionHandling:["Cora wird an den konkreten Prozess angepasst."],cta:"Gespräch anfragen"},
  LOKALER_DIENSTLEISTER:{id:"lokaler-dienstleister",label:"Lokales Dienstleistungsunternehmen",keywords:["dienstleistungsunternehmen","lokaler dienstleister","dienstleister","servicebetrieb"],fields:["leistung","standort","ziel","anliegen","zeitrahmen"],questions:["Welche Leistung soll Cora auf Ihrer Website hauptsächlich unterstützen?"],useCases:["Leistungsanfragen vorqualifizieren","Standort und Bedarf erfassen","Kontaktanfragen strukturieren"],objectionHandling:["Cora ergänzt bestehende Kontaktwege."],cta:"Anfrage vorbereiten"}
});

window.CORA_INTENTS={
  INFORMATION:/^(was|wie|wer|wann|wo|kann|gibt|ist|sind|welche)/i,
  USE_CASE:/wie (kann|würde).*cora|wie.*helfen|wie.*unterstützen/i,
  PROBLEM:/problem|schwier|zu wenig|manuell|zeitaufwand|verpasst|nicht erreichbar/i,
  PRICE:/preis|kosten|monat|setup|€|euro/i,
  PACKAGE:/basic|pro|enterprise|paket|modell|welches.*geeignet|empfehl/i,
  ROI:/lohnt|roi|wirtschaft|rentiert|auszahl|umsatz|wert|break-even/i,
  OBJECTION:/kontaktformular|zu teuer|mitarbeiter|warum.*ki|kaum anfragen|brauche ich/i,
  COMPARISON:/vergleich|unterschied|vs\.?|statt/i,
  PURCHASE:/buchen|kaufen|beauftragen|starten|angebot|termin|gespräch|anfrage vorbereiten/i,
  CONTACT:/kontakt|anrufen|email|e-mail|melden/i,
  INDUSTRY:/fitness|shk|heizung|restaurant|hotel|immobil|makler|kanzlei|beratung|agentur|steuer|arzt|saas|b2b|mittelstand|dienstleister|handwerk/i,
  DEMO_FLOW:/echten ablauf|ablauf zeigen|durchspielen|beispiel/i
};