window.CoraDemo=(()=>{let state=CoraQualification.empty(),history=[],messageCount=0,liveCalls=0;
function renderState(){const m={qIndustry:state.industry||"—",qEmployees:state.companySize??"—",qInquiries:state.monthlyWebsiteInquiries??"—",qNeed:state.goal||"—",qNext:state.nextBestQuestion||"—",qIntent:state.purchaseIntent==="hoch"?"Hoch":state.purchaseIntent==="mittel"?"Mittel":"—",qPlan:state.recommendedPackage||"—",qScore:state.leadScore,qStage:state.conversationStage};Object.entries(m).forEach(([id,v])=>{const x=document.getElementById(id);if(x)x.textContent=v});const q=document.getElementById("qual");if(q)q.classList.toggle("show",messageCount>0)}
function skill(){return Object.values(CORA_SKILLS).find(x=>x.label===state.industry)}
function money(v){return Number(v||0).toLocaleString("de-DE",{style:"currency",currency:"EUR",maximumFractionDigits:0})}
function local(text){const t=text.toLowerCase(),i=CoraQualification.intent(text),s=skill();
if(i==="PRICE"||i==="PACKAGE"){const p=state.recommendedPackage;return"Cora Basic: 895 € einmalig + 495 €/Monat. Cora Pro: 1.495 € einmalig + 895 €/Monat. Cora Enterprise: Preis auf Anfrage. "+(p&&p!=="Prüfung"?"Aktuelle Einordnung: "+p+". ":"")+"Für eine belastbare Pro-Einschätzung bei Ihrem Handwerksbetrieb brauche ich vor allem Ihr monatliches Anfragevolumen und den typischen Auftragswert."; }
if(i==="ROI"){const n=Number(state.monthlyWebsiteInquiries),r=Number(state.conversionRate),a=Number(state.averageOrderValue);if(n>0&&r>0&&a>0){const deals=n*r/100,value=deals*a;return"Auf Basis Ihrer Angaben ergibt sich eine Modellrechnung von ca. "+deals.toLocaleString("de-DE",{maximumFractionDigits:1})+" Abschlüssen bzw. "+money(value)+" Auftragswert pro Monat. Das ist kein von Cora garantierter Zusatzumsatz. Entscheidend ist, welcher Anteil tatsächlich durch bessere Bearbeitung von Website-Anfragen beeinflusst wird."}if(!n)return"Bei einem Handwerksbetrieb kann Pro besonders dann interessant sein, wenn regelmäßig viele Website-Anfragen eingehen und Cora diese vorqualifiziert. Wie viele Website-Anfragen erhalten Sie ungefähr pro Monat?";if(!r)return"Bei "+n+" Website-Anfragen kann ich die Wirtschaftlichkeit als Nächstes über Ihre ungefähre Abschlussquote berechnen. Wie viel Prozent der Anfragen werden heute ungefähr zu Aufträgen?";return"Wenn Sie mir noch den durchschnittlichen Auftragswert nennen, kann ich das Szenario konkret berechnen. Beispiel: 2.500 € oder 5.000 € pro Auftrag. Die Rechnung bleibt eine Modellrechnung und ist keine Umsatzgarantie."}
if(i==="DATA")return"Cora sollte nur die Daten verarbeiten, die für den jeweiligen Use Case erforderlich und freigegeben sind. Für Antworten braucht sie typischerweise Unternehmenswissen; bei einer Anfrage können z. B. Name, Unternehmen, E-Mail, optional Telefon und Anliegen erfasst werden. Welche Daten gespeichert oder an Dienste übertragen werden, hängt von der konkreten Konfiguration ab.";
if(i==="INTEGRATION")return"Cora kann als Webagent in eine bestehende Website eingebunden werden. Für die Demo ist die Website statisch; der Live-Dialog kann über das konfigurierte Backend laufen. Weitere Übergaben wie CRM, E-Mail oder Kalender sollten erst als tatsächlich eingerichtete Integration bezeichnet werden.";
if(i==="OFFER"||i==="PURCHASE")return"Der nächste sinnvolle Schritt ist eine konkrete Anfrage. "+(state.industry?"Für "+state.industry+" kann der bisher erkannte Kontext übernommen werden. ":"")+"Im Formular können Unternehmen, Kontaktdaten und Anliegen strukturiert erfasst werden.";
if(i==="TEST"||/cora.*(testen|ausprobieren)/.test(t))return"Sie testen Cora bereits. Probieren Sie eine konkrete Situation: Branche + Ziel + Anfragevolumen. Beispiel: „Wir sind ein SHK-Betrieb, erhalten 40 Anfragen im Monat und möchten mehr qualifizierte Heizungsanfragen.“";
if(/mitarbeiter/.test(t))return"Cora ersetzt keine Mitarbeiter. Sie kann wiederkehrende Erstfragen, Orientierung und Vorqualifizierung übernehmen, damit Ihr Team mit mehr Kontext in den eigentlichen Kontakt einsteigt.";
if(/kaum.*anfragen/.test(t))return"Cora erzeugt keinen Traffic. Wenn wenige Besucher auf die Website kommen, liegen Reichweite und Angebot davor. Cora setzt an der Bearbeitung vorhandener Website-Kontakte an.";
if(/kann cora.*verkaufen|verkaufen/.test(t))return"Cora kann informieren, Bedarf qualifizieren und zum nächsten Schritt führen. Einen automatischen Verkauf oder eine Umsatzgarantie stellt sie nicht dar.";
if(/warum.*ki/.test(t))return"Der Nutzen liegt weniger im Chatfenster als im Prozess: Fragen werden direkt beantwortet, Anliegen strukturiert und passende nächste Schritte vorbereitet.";
if(/kanzlei/.test(t))return"Für eine Kanzlei kann Cora allgemeine Informationen geben, Anliegen organisatorisch vorsortieren und einen Kontaktweg vorbereiten. Sie darf keine individuelle Rechtsberatung vortäuschen.";
if(/fitness/.test(t))return"Für ein Fitnessstudio kann Cora Trainingsziel, Probetraining, Mitgliedschaft und Kursinteresse erfassen und daraus eine strukturierte Anfrage vorbereiten.";
if(/heizung|shk|handwerk/.test(t))return"Für SHK kann Cora zwischen Heizung, Wärmepumpe, Sanitär und weiteren Leistungen unterscheiden und z. B. Projektart, bestehende Anlage, Einsatzgebiet und Zeitrahmen erfassen.";
if(/restaurant|hotel/.test(t))return"Für Restaurant oder Hotel kann Cora Fragen beantworten und bei Reservierungs- oder Veranstaltungsanfragen Datum, Personen, Anlass und gewünschte Leistung strukturieren.";
if(/immobil/.test(t))return"Für Immobilien kann Cora Kauf/Miete, Objektart, Lage, Budget und Zeitraum erfassen und den nächsten Kontakt vorbereiten.";
if(s)return"Für "+s.label+" kann Cora "+s.roi.toLowerCase()+" Sie erkennt bereits "+(state.goal?"das Ziel „"+state.goal+"“. ":"den Branchenkontext. ")+(state.nextBestQuestion?"Der nächste sinnvolle Schritt wäre: "+state.nextBestQuestion:"Nennen Sie mir noch Ihr Ziel oder Anfragevolumen.") ;
if(i==="USE_CASE"||i==="INDUSTRY")return"Cora kann Website-Fragen beantworten, Anliegen einordnen, relevante Angaben erfassen und bei Kontaktabsicht eine strukturierte Anfrage vorbereiten. Nennen Sie Branche und Ziel, dann wird die Demo konkret.";
return state.industry?"Ich habe "+state.industry+" erkannt. "+(state.nextBestQuestion||"Nennen Sie mir noch Ihr Ziel oder Anfragevolumen."):"Ich kann den Dialog auf Ihre Branche zuschneiden. Nennen Sie Branche, Ziel oder Anfragevolumen."}
async function ask(text){messageCount++;CoraQualification.update(state,text);renderState();const localIntent=CoraQualification.intent(text);const deterministic=["PRICE","PACKAGE","ROI","DATA","OFFER","TEST","INTEGRATION","USE_CASE","PURCHASE"].includes(localIntent);if(deterministic){const reply=local(text);history.push({role:"user",text},{role:"model",text:reply});return{reply,live:false,reason:"deterministic"}}
if(liveCalls>=12){const reply=local(text);history.push({role:"user",text},{role:"model",text:reply});return{reply,live:false,reason:"free-tier-guard"}}const prior=history.slice(-6);try{liveCalls++;const c=new AbortController(),timer=setTimeout(()=>c.abort(),10000);const r=await fetch(CORA_CONFIG.api.chat,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text,history:prior,businessContext:state}),signal:c.signal});clearTimeout(timer);const d=await r.json();if(!r.ok||!d.ok||!d.reply)throw new Error(d?.error||"AI unavailable");const reply=d.reply;history.push({role:"user",text},{role:"model",text:reply});return{reply,live:true,model:d.model||""}}catch{const reply=local(text);history.push({role:"user",text},{role:"model",text:reply});return{reply,live:false,reason:"fallback"}}}
function reset(){state=CoraQualification.empty();history=[];messageCount=0;liveCalls=0;const box=document.getElementById("messages");if(box)box.innerHTML="<div class=\"demoMsg\">Hallo. Ich bin Cora. Testen Sie mich frei. Ich erkenne Branche und Anliegen, behalte Kontext und kann auch Preis-, ROI- und Qualifizierungsfragen beantworten.</div>";renderState();const mode=document.getElementById("demoMode");const status=document.getElementById("demoStatus");if(mode)mode.textContent="Produktdemo · lokale Branchenlogik verfügbar";if(status)status.textContent="● Verbindung wird geprüft …";const input=document.getElementById("demoInput");if(input)input.focus()}
return{getState:()=>state,renderState,ask,reset}})();