window.CoraQualification=(()=>{const empty=()=>({sessionId:crypto.randomUUID?.()||"s-"+Date.now(),industry:"",companySize:null,monthlyWebsiteInquiries:null,goal:"",service:"",projectType:"",location:"",timeline:"",budget:null,conversionRate:null,averageOrderValue:null,purchaseIntent:"niedrig",qualificationStatus:"offen",recommendedPackage:"",missingInformation:[],nextBestQuestion:"",conversationStage:"DISCOVERY",leadScore:0});
function numberAfter(text,re){const m=text.match(re);return m?Number(m[1].replace(/\s/g,"").replace(/\.(?=\d{3})/g,"").replace(",", ".")):null}
function detectIndustry(t){let best=null;for(const s of Object.values(CORA_SKILLS)){let score=0;for(const k of s.keywords){if(t.includes(k))score+=k.length>4?3:2}if(score>0&&(!best||score>best.score))best={label:s.label,score}}return best?.label||""}
function extract(text){const t=String(text||"").toLowerCase(),e={};let m=t.match(/(\d+)\s*(mitarbeiter|personen|beschäftigte|angestellte)/);if(m)e.companySize=+m[1];m=t.match(/(\d+(?:[.,]\d+)?)\s*(website[- ]?anfragen|anfragen|kontakte)/);if(m)e.monthlyWebsiteInquiries=+m[1].replace(",",".");m=t.match(/(?:abschlussquote|abschlussrate|conversion(?:rate)?|abschlüsse)\s*(?:liegt bei|von|:)?\s*(\d+(?:[.,]\d+)?)\s*%|(?:\b)(\d+(?:[.,]\d+)?)\s*%\s*(?:abschlussquote|abschlussrate|conversion(?:rate)?|abschlüsse)/);if(m)e.conversionRate=Math.min(100,+(m[1]||m[2]).replace(",","."));const av=numberAfter(t,/(?:auftragswert|durchschnittlicher auftragswert|auftrag.*wert).*?(\d[\d\s.,]*)\s*(?:€|euro)/);if(av!=null)e.averageOrderValue=av;const bu=numberAfter(t,/(?:budget).*?(\d[\d\s.,]*)\s*(?:€|euro)/);if(bu!=null)e.budget=bu;m=t.match(/(?:plz|postleitzahl)\s*(\d{5})/);if(m)e.location=m[1];e.industry=detectIndustry(t);if(/heizung|wärmepumpe|sanitär|bad/.test(t))e.service=t.match(/heizung|wärmepumpe|sanitär|bad/)?.[0]||"";if(/austausch|neubau|reparatur|wartung|installation/.test(t))e.projectType=t.match(/austausch|neubau|reparatur|wartung|installation/)?.[0]||"";if(/mehr.*(anfragen|leads|kunden|aufträge)|qualifizierte.*anfragen/.test(t))e.goal="Mehr qualifizierte Anfragen";if(/lohnt|zahlt sich|wirtschaft|rechnet sich|rentiert|roi|wirtschaftlich|mehrwert|bringt.*pro|pro.*bringt/.test(t))e.goal="Wirtschaftlichkeit prüfen";if(/reserv/.test(t))e.goal="Reservierungen";if(/termin/.test(t))e.goal="Terminanfragen";if(/buchen|beauftragen|angebot|starten|gespräch|kaufen/.test(t))e.purchaseIntent="hoch";else if(/interess|möchte|brauche|suche|überlege/.test(t))e.purchaseIntent="mittel";return e}
function intent(text){const t=String(text||"").trim();const order=["ROI","PRICE","DATA","OFFER","TEST","INTEGRATION","USE_CASE","PACKAGE","OBJECTION","COMPARISON","PURCHASE","CONTACT","PROBLEM","INDUSTRY","DEMO_FLOW","INFORMATION"];for(const k of order){const r=CORA_INTENTS[k];if(r&&r.test(t))return k}return"INFORMATION"}
function merge(s,p){for(const[k,v]of Object.entries(p||{}))if(v!==""&&v!==null&&v!==undefined)s[k]=v;return s}
function score(s){let n=0;if(s.industry)n+=15;if(s.goal)n+=10;if(s.monthlyWebsiteInquiries!=null)n+=15;if(s.service)n+=8;if(s.projectType)n+=6;if(s.conversionRate!=null)n+=10;if(s.averageOrderValue!=null)n+=10;if(s.companySize!=null)n+=5;if(s.purchaseIntent==="mittel")n+=8;if(s.purchaseIntent==="hoch")n+=15;return Math.min(100,n)}
function packageFor(s){if(s.monthlyWebsiteInquiries>=100)return"Enterprise";if(s.monthlyWebsiteInquiries>=25||s.purchaseIntent==="hoch"&&s.goal)return"Pro";if(s.monthlyWebsiteInquiries!=null||s.conversionRate!=null||s.averageOrderValue!=null)return"Prüfung";return""}
function next(s){if(!s.industry)return"Welche Branche oder welches Geschäft betreiben Sie?";if(s.monthlyWebsiteInquiries==null)return"Wie viele Website-Anfragen erhalten Sie ungefähr pro Monat?";if(s.goal==="Wirtschaftlichkeit prüfen"){if(s.conversionRate==null)return"Wie hoch ist Ihre ungefähre Abschlussquote – grob reicht, z. B. 10–20 %?";if(s.averageOrderValue==null)return"Wie hoch ist Ihr durchschnittlicher Auftragswert?";return""}const skill=Object.values(CORA_SKILLS).find(x=>x.label===s.industry);return skill?.questions?.[0]||""}
function update(s,text){const p=extract(text);merge(s,p);s.leadScore=score(s);s.recommendedPackage=packageFor(s);s.nextBestQuestion=next(s);s.missingInformation=s.nextBestQuestion?[s.nextBestQuestion]:[];s.conversationStage=s.purchaseIntent==="hoch"?"HIGH_INTENT":s.leadScore>=70?"QUALIFICATION":s.leadScore>=35?"CONTEXT":"DISCOVERY";s.qualificationStatus=s.leadScore>=70?"qualifiziert":s.leadScore>=35?"in Prüfung":"offen";return s}
return{empty,extract,intent,update,score,packageFor}})();