const test=require("node:test");const assert=require("node:assert/strict");global.window=global;global.crypto=require("node:crypto").webcrypto;require("../js/config.js");require("../js/demo-data.js");require("../js/qualification.js");
test("SHK and company size are extracted",()=>{const s=CoraQualification.empty();CoraQualification.update(s,"Wir sind ein SHK-Betrieb mit 20 Mitarbeitern.");assert.equal(s.industry,"Handwerk / SHK");assert.equal(s.companySize,20)});
test("website inquiries are remembered",()=>{const s=CoraQualification.empty();CoraQualification.update(s,"Wir bekommen 40 Website-Anfragen im Monat.");assert.equal(s.monthlyWebsiteInquiries,40);CoraQualification.update(s,"Wir wollen mehr qualifizierte Heizungsanfragen.");assert.equal(s.monthlyWebsiteInquiries,40);assert.equal(s.service,"heizung");assert.equal(s.goal,"Mehr qualifizierte Anfragen")});
test("ROI inputs are extracted",()=>{const s=CoraQualification.empty();CoraQualification.update(s,"40 Anfragen, Abschlussquote 20 %, durchschnittlicher Auftragswert 5000 €.");assert.equal(s.monthlyWebsiteInquiries,40);assert.equal(s.conversionRate,20);assert.equal(s.averageOrderValue,5000)});
test("package and purchase intent",()=>{const s=CoraQualification.empty();CoraQualification.update(s,"Wir haben 40 Website-Anfragen und möchten Cora Pro buchen.");assert.equal(s.recommendedPackage,"Pro");assert.equal(s.purchaseIntent,"hoch");assert.equal(s.conversationStage,"HIGH_INTENT")});
test("industry coverage",()=>{for(const input of ["Ich habe eine Kanzlei.","Wir betreiben ein Hotel.","Ich bin Immobilienmakler.","Wir sind eine Steuerberatung.","Wir haben eine Arztpraxis.","Wir verkaufen B2B-Software.","Wir sind ein Mittelstandsunternehmen.","Wir haben ein Restaurant.","Wir führen eine Agentur."]){const s=CoraQualification.empty();CoraQualification.update(s,input);assert.ok(s.industry,input)}});
test("context persists and next question is singular",()=>{const s=CoraQualification.empty();CoraQualification.update(s,"Ich habe ein Fitnessstudio mit 300 Mitgliedern und möchte mehr Probetrainings.");assert.equal(s.industry,"Fitnessstudio");assert.equal(s.companySize,300);assert.equal(s.goal,"Mehr Probetrainings");assert.ok(s.nextBestQuestion);assert.equal(s.missingInformation.length,1);CoraQualification.update(s,"Wir bekommen 40 Website-Anfragen im Monat.");assert.equal(s.companySize,300);assert.equal(s.monthlyWebsiteInquiries,40)});
test("score is deterministic and bounded",()=>{const s=CoraQualification.empty();CoraQualification.update(s,"Ich bin Makler und möchte 40 Website-Anfragen besser qualifizieren. Abschlussquote 20 %, Auftragswert 5000 €.");assert.ok(s.leadScore>=0&&s.leadScore<=100);assert.equal(CoraQualification.score(s),s.leadScore)});
test("price intent and legal boundary",()=>{const s=CoraQualification.empty();CoraQualification.update(s,"Was kostet Cora?");assert.equal(CoraQualification.intent("Was kostet Cora?"),"INFORMATION");assert.equal(s.industry,"");});
